name: Node.js CI & Publish

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🔧 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'

      - name: 📦 Install dependencies
        run: npm i

      - name: 🛠 Build project
        run: npm run build

      - name: ✅ Run tests
        run: npm test

      - name: 🚀 Publish to npm (Node 22 only)
        if: matrix.node-version == '22.x'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
